<?php
/**
 * Generate a single, clean, cPanel-importable SQL file for production.
 *
 * Run from project root:
 *   php scripts/generate_production_sql.php
 *
 * Output: database/shena_production.sql
 */

$rootPath  = dirname(__DIR__);
$schemaFile = $rootPath . '/database/schema.sql';
$outputFile = $rootPath . '/database/shena_production.sql';

if (!file_exists($schemaFile)) {
    fwrite(STDERR, "ERROR: database/schema.sql not found.\n");
    exit(1);
}

$schema = file_get_contents($schemaFile);

// ── 1. Strip the auto-generated header comment that embeds local credentials ─
$schema = preg_replace('/^-- Generated by.*?\n-- Source \.env.*?\n-- DB_HOST.*?\n/sm', '', $schema);

// ── 1b. Normalise collation: utf8mb4_0900_ai_ci is MySQL 8.0+ only.
//    Shared hosts (HostPinnacle, InfinityFree) run MySQL 5.7 → use unicode_ci.
$schema = str_replace(
    ['utf8mb4_0900_ai_ci', 'CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci'],
    ['utf8mb4_unicode_ci', 'CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    $schema
);

// ── 2. Remove DEFINER=`user`@`host` from views (not portable to shared hosting) ─
$schema = preg_replace(
    '/CREATE ALGORITHM=UNDEFINED DEFINER=`[^`]+`@`[^`]+` SQL SECURITY DEFINER /',
    'CREATE OR REPLACE VIEW ',
    $schema
);
$schema = preg_replace('/CREATE ALGORITHM=UNDEFINED /', '', $schema);

// ── 3. Reset AUTO_INCREMENT counters (fresh install, no test data) ─────────────
$schema = preg_replace('/\bAUTO_INCREMENT=\d+\b/', '', $schema);

// ── 4. Update payments table: add STK-push columns & updated payment_type enum ──
//    Find the payments CREATE TABLE and inject missing columns before PRIMARY KEY.
$stkCols = "  `merchant_request_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'M-Pesa Merchant Request ID',\n"
         . "  `checkout_request_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'M-Pesa Checkout Request ID',\n"
         . "  `result_code` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'M-Pesa result code',\n"
         . "  `result_desc` text COLLATE utf8mb4_unicode_ci COMMENT 'M-Pesa result description',\n";

// Inject before the `auto_matched` column (last column before PRIMARY KEY in payments)
$schema = preg_replace(
    '/(  `auto_matched` tinyint\(1\) DEFAULT \'0\',\n  PRIMARY KEY \(`id`\))/s',
    $stkCols . "  `auto_matched` tinyint(1) DEFAULT '0',\n  PRIMARY KEY (`id`)",
    $schema
);

// Add the STK column indexes before the payments FK constraint
$stkIdxs = "  KEY `idx_payments_checkout_request` (`checkout_request_id`),\n"
          . "  KEY `idx_payments_merchant_request` (`merchant_request_id`),\n";
$schema = preg_replace(
    '/(  CONSTRAINT `payments_ibfk_1`)/s',
    $stkIdxs . "  CONSTRAINT `payments_ibfk_1`",
    $schema
);

// Update payment_type enum to include upgrade + other
$schema = str_replace(
    "`payment_type` enum('registration','monthly','reactivation','penalty') COLLATE utf8mb4_unicode_ci DEFAULT 'monthly'",
    "`payment_type` enum('registration','monthly','reactivation','upgrade','penalty','other') COLLATE utf8mb4_unicode_ci DEFAULT 'monthly'",
    $schema
);

// ── 5. Build extensions block (new tables, views, stored procedure) ───────────
$extensions = <<<'SQL'

-- ============================================================
-- POST-SCHEMA EXTENSIONS (added after Feb-23-2026 snapshot)
-- ============================================================

-- ── support_tickets ──────────────────────────────────────────
DROP TABLE IF EXISTS `support_tickets`;
CREATE TABLE `support_tickets` (
  `id` int NOT NULL AUTO_INCREMENT,
  `member_id` int NOT NULL,
  `user_id` int NOT NULL,
  `subject` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `priority` enum('low','normal','high','urgent') COLLATE utf8mb4_unicode_ci DEFAULT 'normal',
  `status` enum('open','in_progress','resolved','closed') COLLATE utf8mb4_unicode_ci DEFAULT 'open',
  `response` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `responded_by` int DEFAULT NULL,
  `responded_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_support_member` (`member_id`),
  KEY `idx_support_status` (`status`),
  KEY `idx_support_priority` (`priority`),
  KEY `idx_support_created` (`created_at`),
  CONSTRAINT `support_tickets_ibfk_1` FOREIGN KEY (`member_id`) REFERENCES `members` (`id`) ON DELETE CASCADE,
  CONSTRAINT `support_tickets_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `support_tickets_ibfk_3` FOREIGN KEY (`responded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── mpesa_stk_push_logs ──────────────────────────────────────
DROP TABLE IF EXISTS `mpesa_stk_push_logs`;
CREATE TABLE `mpesa_stk_push_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `payment_id` int DEFAULT NULL,
  `merchant_request_id` varchar(100) NOT NULL,
  `checkout_request_id` varchar(100) NOT NULL,
  `phone_number` varchar(20) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `account_reference` varchar(100) DEFAULT NULL,
  `transaction_desc` varchar(255) DEFAULT NULL,
  `result_code` varchar(10) DEFAULT NULL,
  `result_desc` text DEFAULT NULL,
  `mpesa_receipt_number` varchar(50) DEFAULT NULL,
  `transaction_date` datetime DEFAULT NULL,
  `request_sent_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `callback_received_at` datetime DEFAULT NULL,
  `callback_data` text DEFAULT NULL COMMENT 'Full callback JSON',
  `status` enum('pending','success','failed','timeout') DEFAULT 'pending',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_stk_checkout_request` (`checkout_request_id`),
  KEY `idx_stk_merchant_request` (`merchant_request_id`),
  KEY `idx_stk_phone_number` (`phone_number`),
  KEY `idx_stk_status` (`status`),
  KEY `idx_stk_request_sent_at` (`request_sent_at`),
  CONSTRAINT `mpesa_stk_push_logs_ibfk_1` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── mpesa_configuration ──────────────────────────────────────
DROP TABLE IF EXISTS `mpesa_configuration`;
CREATE TABLE `mpesa_configuration` (
  `id` int NOT NULL AUTO_INCREMENT,
  `config_key` varchar(100) NOT NULL,
  `config_value` text NOT NULL,
  `environment` enum('sandbox','production') DEFAULT 'sandbox',
  `description` text DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_key_env` (`config_key`,`environment`),
  KEY `idx_mpesa_config_key` (`config_key`),
  KEY `idx_mpesa_environment` (`environment`),
  KEY `idx_mpesa_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── mpesa_config_audit ───────────────────────────────────────
DROP TABLE IF EXISTS `mpesa_config_audit`;
CREATE TABLE `mpesa_config_audit` (
  `id` int NOT NULL AUTO_INCREMENT,
  `config_id` int NOT NULL,
  `config_key` varchar(100) NOT NULL,
  `old_value` text DEFAULT NULL,
  `new_value` text NOT NULL,
  `changed_by` int DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_mpesa_audit_config_id` (`config_id`),
  KEY `idx_mpesa_audit_changed_at` (`changed_at`),
  CONSTRAINT `mpesa_config_audit_ibfk_1` FOREIGN KEY (`config_id`) REFERENCES `mpesa_configuration` (`id`) ON DELETE CASCADE,
  CONSTRAINT `mpesa_config_audit_ibfk_2` FOREIGN KEY (`changed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── STK Push Views ───────────────────────────────────────────
DROP VIEW IF EXISTS `vw_pending_stk_pushes`;
CREATE OR REPLACE VIEW `vw_pending_stk_pushes` AS
SELECT
  l.id,
  l.checkout_request_id,
  l.phone_number,
  l.amount,
  l.account_reference,
  l.status,
  l.request_sent_at,
  TIMESTAMPDIFF(MINUTE, l.request_sent_at, NOW()) AS minutes_pending,
  p.id AS payment_id,
  p.member_id,
  p.payment_type,
  m.member_number,
  CONCAT(u.first_name, ' ', u.last_name) AS member_name
FROM mpesa_stk_push_logs l
LEFT JOIN payments p ON l.payment_id = p.id
LEFT JOIN members m ON p.member_id = m.id
LEFT JOIN users u ON m.user_id = u.id
WHERE l.status = 'pending'
  AND TIMESTAMPDIFF(MINUTE, l.request_sent_at, NOW()) < 5
ORDER BY l.request_sent_at DESC;

DROP VIEW IF EXISTS `vw_failed_stk_pushes`;
CREATE OR REPLACE VIEW `vw_failed_stk_pushes` AS
SELECT
  l.id,
  l.checkout_request_id,
  l.phone_number,
  l.amount,
  l.result_code,
  l.result_desc,
  l.request_sent_at,
  l.callback_received_at,
  p.id AS payment_id,
  p.member_id,
  m.member_number,
  CONCAT(u.first_name, ' ', u.last_name) AS member_name
FROM mpesa_stk_push_logs l
LEFT JOIN payments p ON l.payment_id = p.id
LEFT JOIN members m ON p.member_id = m.id
LEFT JOIN users u ON m.user_id = u.id
WHERE l.status = 'failed'
ORDER BY l.request_sent_at DESC;

-- ── Stored procedure: timeout old pending STK pushes ─────────
DROP PROCEDURE IF EXISTS `timeout_old_stk_pushes`;
DELIMITER //
CREATE PROCEDURE `timeout_old_stk_pushes`()
BEGIN
  UPDATE mpesa_stk_push_logs
  SET status = 'timeout',
      result_desc = 'Request timed out – no callback within 5 minutes',
      updated_at = NOW()
  WHERE status = 'pending'
    AND TIMESTAMPDIFF(MINUTE, request_sent_at, NOW()) >= 5;

  UPDATE payments p
  INNER JOIN mpesa_stk_push_logs l ON p.transaction_reference = l.checkout_request_id
  SET p.status = 'failed',
      p.notes = CONCAT(COALESCE(p.notes, ''), ' [STK Timeout]')
  WHERE l.status = 'timeout'
    AND p.status = 'pending';
END //
DELIMITER ;

-- ── Seed: initial sms_credits row ────────────────────────────
INSERT IGNORE INTO `sms_credits` (`id`, `balance`, `low_balance_threshold`)
VALUES (1, 0, 100);

-- ── Seed: mpesa_configuration defaults (update values before going live) ──────
INSERT INTO `mpesa_configuration` (`config_key`, `config_value`, `environment`, `description`) VALUES
('business_shortcode', '174379',                                       'sandbox',    'Sandbox Business Shortcode'),
('business_shortcode', '4163987',                                      'production', 'Production Business Shortcode'),
('passkey',            'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919', 'sandbox', 'Sandbox STK Passkey'),
('passkey',            'REPLACE_WITH_PROD_PASSKEY_FROM_SAFARICOM',     'production', 'Production STK Passkey'),
('api_url',            'https://sandbox.safaricom.co.ke',              'sandbox',    'Sandbox API Base URL'),
('api_url',            'https://api.safaricom.co.ke',                  'production', 'Production API Base URL'),
('callback_url',       'https://shenacompanion.co.ke/public/mpesa-stk-callback.php', 'production', 'STK Callback URL'),
('c2b_callback_url',   'https://shenacompanion.co.ke/public/mpesa-c2b-callback.php', 'production', 'C2B Callback URL')
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SQL;

// ── 6. Remove the trailing SET FOREIGN_KEY_CHECKS restore from schema.sql ────
//    (we'll add it back at the very end with the extensions block)
$schema = preg_replace('/\nSET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\s*$/', '', $schema);

// ── 7. Build final output ─────────────────────────────────────────────────────
$header  = "-- =============================================================\n";
$header .= "-- Shena Companion Welfare Association -- PRODUCTION DATABASE\n";
$header .= "-- Generated : " . date('Y-m-d H:i:s') . "\n";
$header .= "-- Usage     : Import via cPanel -> phpMyAdmin -> Import tab\n";
$header .= "--             Create an empty database first, then import.\n";
$header .= "-- IMPORTANT : Update REPLACE_WITH_* placeholders and YOURDOMAIN.COM\n";
$header .= "--             before importing into production.\n";
$header .= "-- =============================================================\n\n";

$output = $header . $schema . $extensions;

file_put_contents($outputFile, $output);
echo "Generated: database/shena_production.sql (" . number_format(strlen($output)) . " bytes)\n";
