<?php

/**
 * Prepare SHENA member import files from the contribution workbook.
 *
 * Usage:
 *   php tools/shena_member_import_prepare.php "C:\path\CONTRIBUTION LIST TO WEB PAGE.xlsx"
 */

if ($argc < 2) {
    fwrite(STDERR, "Usage: php tools/shena_member_import_prepare.php <file.xlsx>\n");
    exit(1);
}

$xlsx = $argv[1];
if (!is_file($xlsx)) {
    fwrite(STDERR, "Workbook not found: {$xlsx}\n");
    exit(1);
}

$root = dirname(__DIR__);
$outDir = $root . '/storage/imports/member_import_' . date('Ymd_His');
if (!is_dir($outDir) && !mkdir($outDir, 0777, true)) {
    fwrite(STDERR, "Unable to create output directory: {$outDir}\n");
    exit(1);
}

$packages = require $root . '/config/packages.php';
$rows = readWorkbookRows($xlsx);

$valid = [];
$rejected = [];
$seenPhones = [];
$seenIds = [];

foreach ($rows as $source) {
    $registrationCode = trim((string)($source['registration_code'] ?? ''));
    $fullName = normalizeSpaces((string)($source['full_name'] ?? ''));
    $phone = normalizePhone((string)($source['phone'] ?? ''));
    $idNumber = normalizeId((string)($source['id_number'] ?? ''));
    $gender = normalizeGender((string)($source['gender'] ?? ''));
    $yob = normalizeYear((string)($source['yob'] ?? ''));
    $amount = normalizeAmount((string)($source['amount'] ?? ''));
    $county = normalizeSpaces((string)($source['county'] ?? ''));
    $village = normalizeSpaces((string)($source['village'] ?? ''));

    $errors = [];
    if ($fullName === '') {
        $errors[] = 'Missing principal member name';
    }
    if ($phone === '') {
        $errors[] = 'Missing or invalid phone';
    }
    if ($idNumber === '') {
        $errors[] = 'Missing ID number';
    }
    if ($gender === '') {
        $errors[] = 'Missing or invalid gender';
    }
    if ($yob === '') {
        $errors[] = 'Missing or invalid year of birth';
    }
    if ($amount <= 0) {
        $errors[] = 'Missing or invalid contribution amount';
    }
    if ($phone !== '' && isset($seenPhones[$phone])) {
        $errors[] = 'Duplicate phone in workbook';
    }
    if ($idNumber !== '' && isset($seenIds[$idNumber])) {
        $errors[] = 'Duplicate ID number in workbook';
    }

    $package = inferPackageOrFallback($yob !== '' ? (int)$yob : null, $amount, $packages);

    [$firstName, $lastName] = splitName($fullName);
    if ($lastName === '') {
        $lastName = '-';
    }

    $dateOfBirth = $yob !== '' ? $yob . '-01-01' : '';
    $email = $idNumber !== '' ? 'member-' . strtolower($idNumber) . '@import.shena.local' : '';
    $addressParts = array_filter([$village, $county]);
    $address = implode(', ', $addressParts);

    $prepared = [
        'source_sheet' => $source['sheet'] ?? '',
        'source_row' => $source['row'] ?? '',
        'source_registration_code' => $registrationCode,
        'first_name' => $firstName,
        'last_name' => $lastName,
        'full_name' => $fullName,
        'phone' => $phone,
        'email' => $email,
        'id_number' => $idNumber,
        'gender' => $gender,
        'date_of_birth' => $dateOfBirth,
        'yob' => $yob,
        'county' => $county,
        'village' => $village,
        'address' => $address,
        'monthly_contribution' => number_format($amount, 2, '.', ''),
        'package_key' => $package['key'] ?? '',
        'package' => $package['category'] ?? '',
        'import_status' => 'pending_activation',
        'notes' => 'Imported from contribution workbook. Member number generated by system during import.',
    ];

    if ($errors) {
        $prepared['errors'] = implode('; ', $errors);
        $rejected[] = $prepared;
        continue;
    }

    $seenPhones[$phone] = true;
    $seenIds[$idNumber] = true;
    $valid[] = $prepared;
}

writeCsv($outDir . '/members_import_clean.csv', $valid, cleanHeaders());
writeCsv($outDir . '/members_import_rejected.csv', $rejected, array_merge(cleanHeaders(), ['errors']));
writeJson($outDir . '/members_import_summary.json', [
    'source' => $xlsx,
    'generated_at' => date('c'),
    'valid_rows' => count($valid),
    'rejected_rows' => count($rejected),
    'member_number_policy' => 'Generated by production system using MemberNumberHelper::generateCanonical(); Excel registration code is stored only as source_registration_code.',
]);

echo "Prepared import files in: {$outDir}\n";
echo "Valid rows: " . count($valid) . "\n";
echo "Rejected rows: " . count($rejected) . "\n";

function readWorkbookRows(string $xlsx): array
{
    $zip = new ZipArchive();
    if ($zip->open($xlsx) !== true) {
        throw new RuntimeException("Unable to open workbook");
    }

    $sharedStrings = [];
    $sharedXml = $zip->getFromName('xl/sharedStrings.xml');
    if ($sharedXml !== false) {
        $xml = simplexml_load_string($sharedXml);
        foreach ($xml->si as $si) {
            $parts = [];
            if (isset($si->t)) {
                $parts[] = (string)$si->t;
            }
            foreach ($si->r ?? [] as $run) {
                $parts[] = (string)$run->t;
            }
            $sharedStrings[] = implode('', $parts);
        }
    }

    $all = [];
    for ($sheet = 1; $sheet <= 3; $sheet++) {
        $sheetXml = $zip->getFromName("xl/worksheets/sheet{$sheet}.xml");
        if ($sheetXml === false) {
            continue;
        }

        $xml = simplexml_load_string($sheetXml);
        foreach ($xml->sheetData->row as $row) {
            $rowNumber = (int)$row['r'];
            $cells = [];
            foreach ($row->c as $cell) {
                $ref = (string)$cell['r'];
                preg_match('/^[A-Z]+/', $ref, $m);
                $col = $m[0] ?? '';
                $type = (string)$cell['t'];
                if ($type === 's') {
                    $value = $sharedStrings[(int)$cell->v] ?? '';
                } elseif ($type === 'inlineStr') {
                    $value = (string)$cell->is->t;
                } else {
                    $value = isset($cell->v) ? (string)$cell->v : '';
                }
                $cells[$col] = trim($value);
            }

            if ($sheet === 1 && $rowNumber <= 2) {
                continue;
            }

            $mapped = [
                'sheet' => 'Sheet' . $sheet,
                'row' => $rowNumber,
                'registration_code' => $cells['A'] ?? '',
                'full_name' => $cells['B'] ?? '',
                'phone' => $sheet === 1 ? ($cells['F'] ?? '') : ($cells['C'] ?? ''),
                'amount' => $sheet === 1 ? ($cells['G'] ?? '') : ($cells['D'] ?? ''),
                'yob' => $sheet === 1 ? ($cells['C'] ?? '') : '',
                'gender' => $sheet === 1 ? ($cells['D'] ?? '') : '',
                'id_number' => $sheet === 1 ? ($cells['E'] ?? '') : '',
                'county' => $sheet === 1 ? ($cells['H'] ?? '') : '',
                'village' => $sheet === 1 ? ($cells['I'] ?? '') : '',
            ];

            if (implode('', array_map('strval', $mapped)) === ('Sheet' . $sheet . $rowNumber)) {
                continue;
            }
            if (trim((string)$mapped['full_name']) === '') {
                continue;
            }
            $all[] = $mapped;
        }
    }

    $zip->close();
    return $all;
}

function cleanHeaders(): array
{
    return [
        'source_sheet',
        'source_row',
        'source_registration_code',
        'first_name',
        'last_name',
        'full_name',
        'phone',
        'email',
        'id_number',
        'gender',
        'date_of_birth',
        'yob',
        'county',
        'village',
        'address',
        'monthly_contribution',
        'package_key',
        'package',
        'import_status',
        'notes',
    ];
}

function writeCsv(string $path, array $rows, array $headers): void
{
    $fh = fopen($path, 'w');
    fputcsv($fh, $headers);
    foreach ($rows as $row) {
        $line = [];
        foreach ($headers as $header) {
            $line[] = $row[$header] ?? '';
        }
        fputcsv($fh, $line);
    }
    fclose($fh);
}

function writeJson(string $path, array $data): void
{
    file_put_contents($path, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
}

function normalizeSpaces(string $value): string
{
    return trim(preg_replace('/\s+/', ' ', $value));
}

function normalizePhone(string $phone): string
{
    $digits = preg_replace('/\D+/', '', $phone);
    if ($digits === '') {
        return '';
    }
    if (strlen($digits) === 9) {
        return '254' . $digits;
    }
    if (strlen($digits) === 10 && $digits[0] === '0') {
        return '254' . substr($digits, 1);
    }
    if (strlen($digits) === 12 && substr($digits, 0, 3) === '254') {
        return $digits;
    }
    return '';
}

function normalizeId(string $id): string
{
    return preg_replace('/[^A-Za-z0-9]/', '', $id);
}

function normalizeGender(string $gender): string
{
    $gender = strtoupper(substr(trim($gender), 0, 1));
    if ($gender === 'M') {
        return 'male';
    }
    if ($gender === 'F') {
        return 'female';
    }
    return '';
}

function normalizeYear(string $year): string
{
    $year = preg_replace('/\D+/', '', $year);
    if (strlen($year) !== 4) {
        return '';
    }
    $int = (int)$year;
    if ($int < 1926 || $int > (int)date('Y') - 18) {
        return '';
    }
    return (string)$int;
}

function normalizeAmount(string $amount): float
{
    return (float)preg_replace('/[^0-9.]/', '', $amount);
}

function inferPackageOrFallback(?int $yob, float $amount, array $packages): array
{
    $candidates = [];
    if ($yob !== null) {
        $age = (int)date('Y') - $yob;
        foreach ($packages as $key => $package) {
            $fee = (float)($package['monthly_contribution'] ?? 0);
            $min = (int)($package['age_min'] ?? 18);
            $max = (int)($package['age_max'] ?? 100);
            if (abs($fee - $amount) < 0.01 && $age >= $min && $age <= $max) {
                $candidates[$key] = $package;
            }
        }
    }

    $priority = [
        'individual_below_70',
        'individual_71_80',
        'individual_81_90',
        'individual_91_100',
        'couple_below_70',
        'couple_children_below_70',
        'couple_children_parents_below_70',
        'couple_children_parents_70_80',
        'couple_children_parents_81_90',
        'couple_children_parents_91_100',
        'couple_children_parents_inlaws_below_70',
        'couple_children_parents_inlaws_71_80',
        'couple_children_parents_inlaws_81_90',
        'couple_children_parents_inlaws_91_100',
        'executive_below_70',
        'executive_above_70',
    ];

    foreach ($priority as $key) {
        if (isset($candidates[$key])) {
            return ['key' => $key, 'category' => $candidates[$key]['category'] ?? 'individual'];
        }
    }

    $key = array_key_first($candidates);
    if ($key !== null) {
        return ['key' => $key, 'category' => $candidates[$key]['category'] ?? 'individual'];
    }

    return ['key' => '', 'category' => fallbackPackageCategory($amount)];
}

function fallbackPackageCategory(float $amount): string
{
    if ($amount <= 100) {
        return 'individual';
    }
    if ($amount <= 200) {
        return 'family';
    }
    if ($amount <= 350) {
        return 'extended_family_1';
    }
    if ($amount <= 650) {
        return 'extended_family_2';
    }

    return 'executive';
}

function splitName(string $fullName): array
{
    $parts = preg_split('/\s+/', trim($fullName)) ?: [];
    $first = array_shift($parts) ?: '';
    $last = trim(implode(' ', $parts));
    return [$first, $last];
}
